@prod = 
@dev =
@local = http://[::1]:5173

@pwh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoicHdoIiwicm9sZSI6ImF1dGhvciJ9LCJpYXQiOjE2ODIwODkzNjYsImV4cCI6MTY4MjA5Mjk2Nn0.mf4waCq-SfMUsCKti7GbojEQyBhJXUNBePLgibyTMyk

@nwh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoibndoIiwicm9sZSI6ImF1dGhvciJ9LCJpYXQiOjE2ODE5ODQwNDEsImV4cCI6MTY4MTk4NzY0MX0.3WuYkA5hzAXT-uWnBYX5SZaUykjwKZ6mqd1YpjsIQW4

###
POST {{local}}/api/auth/login
Content-Type: application/json

{
  "username": "pwh",
  "password": "nilar"
}

###
GET {{local}}/api/configs
Authorization: BeanNoodle {{pwh_token}}

###
GET {{local}}/api/configs/main

###
POST {{local}}/api/configs
Content-Type: application/json
Authorization: BeanNoodle {{pwh_token}}

{
  "name": "private",
  "appName": "songs and stories"
}

###
PATCH {{local}}/api/configs/main
Content-Type: application/json
Authorization: BeanNoodle {{pwh_token}}

{
  "appName": "songs and stories",
  "footer": {
    "hello": "world"
  }
}

###
DELETE {{local}}/api/configs/main
Authorization: BeanNoodle {{pwh_token}}