@prod = 
@dev =
@local = http://localhost:5173


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4ifSwiaWF0IjoxNjg5ODI4NzQ4LCJleHAiOjE2ODk4MzIzNDh9.Xi2afBuhD0qyPefxLa23WVXb6J3q9rgvlF0ThhbEaa8

###
POST {{local}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "nilar"
}

###
GET {{local}}/api/songs
Authorization: BeanNoodle {{token}}

###
GET {{local}}/api/songs/6440c4c0c58c3e074af7c54b
Authorization: BeanNoodle {{token}}

###
POST {{local}}/api/songs
Content-Type: application/json
Authorization: BeanNoodle {{token}}

{
  "src": "https://github.com/pwhb/public/blob/main/music/Freddie%20Mercury%20-%20Living%20On%20My%20Own%20(1993%20Remix%20Remastered)-HTdd8QxifbY.webm?raw=true",
  "title": "Living On My Own",
  "artist": "Freddie Mercury",
  "youtube": "https://youtu.be/HTdd8QxifbY",
  "active": false
}

###
PATCH {{local}}/api/songs/6440eab19c2e9a9153bfe59a
Content-Type: application/json

{
  "active": true
}

###
DELETE {{local}}/api/songs/6443e0718ab15ff98859140d
Authorization: BeanNoodle {{token}}