@prod = 
@dev =
@local = http://[::1]:5173

@pwh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoicHdoIiwicm9sZSI6ImF1dGhvciJ9LCJpYXQiOjE2ODE5ODM2NTMsImV4cCI6MTY4MTk4NzI1M30.c7X1w37pO3z9QCtiWQjhOOA2_iVCnIpFyabnUWt6oeo

@nwh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoibndoIiwicm9sZSI6ImF1dGhvciJ9LCJpYXQiOjE2ODIxMzY3MzEsImV4cCI6MTY4MjE0MDMzMX0.Uqu3z3eE_GMqJUYquPZZWyMnCobOSNdUn-z56B0V-GI

###
POST {{local}}/api/auth/login
Content-Type: application/json

{
  "username": "nwh",
  "password": "nilar"
}

###
GET {{local}}/api/users
Authorization: BeanNoodle {{nwh_token}}

###
GET {{local}}/api/users/6440c4c0c58c3e074af7c54b

###
POST {{local}}/api/users
Content-Type: application/json
Authorization: BeanNoodle {{nwh_token}}

{
  "username": "admin",
  "penName": "admin",
  "password": "nilar",
  "role":"admin"
}

###
PATCH {{local}}/api/users
Content-Type: application/json
Authorization: BeanNoodle {{pwh_token}}

{
   "penName": "pinkius",
   "firstName": "Phone",
   "lastName": "Waiyam Hein"
}

###
DELETE {{local}}/api/users/6441081625abcc30ca3651e3